// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfhZQ3yMh7JKJw4bR9xevWUhkJ6JM-6sk',
    appId: '1:148007581176:web:e112f9ccbbacbecf94920d',
    messagingSenderId: '148007581176',
    projectId: 'coffeeft-31b1e',
    authDomain: 'coffeeft-31b1e.firebaseapp.com',
    storageBucket: 'coffeeft-31b1e.appspot.com',
    measurementId: 'G-6P1EPESYKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0odoISlg-yiKQ9Jk0iL-AJHaOcx7NetQ',
    appId: '1:148007581176:android:8fa49c3a62b43ac094920d',
    messagingSenderId: '148007581176',
    projectId: 'coffeeft-31b1e',
    storageBucket: 'coffeeft-31b1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRRrSWSnOey2xpiKyM_8dChosXcqhC9SY',
    appId: '1:148007581176:ios:152fea2848b55f8094920d',
    messagingSenderId: '148007581176',
    projectId: 'coffeeft-31b1e',
    storageBucket: 'coffeeft-31b1e.appspot.com',
    iosClientId: '148007581176-dup54c4j8i8onv99p9j4u8c4agk3e2v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRRrSWSnOey2xpiKyM_8dChosXcqhC9SY',
    appId: '1:148007581176:ios:152fea2848b55f8094920d',
    messagingSenderId: '148007581176',
    projectId: 'coffeeft-31b1e',
    storageBucket: 'coffeeft-31b1e.appspot.com',
    iosClientId: '148007581176-dup54c4j8i8onv99p9j4u8c4agk3e2v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeft',
  );
}
