export const data = [{
    "APMC": "Ahmednagar",
    "Commodity": "Bajri",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 79,
    "min_price": 1406,
    "max_price": 1538,
    "modal_price": 1463,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Bajri",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 106,
    "min_price": 1788,
    "max_price": 1925,
    "modal_price": 1875,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Wheat(Husked)",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 1253,
    "min_price": 1572,
    "max_price": 1890,
    "modal_price": 1731,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Wheat(Husked)",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 387,
    "min_price": 1750,
    "max_price": 2220,
    "modal_price": 1999,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Sorgum(Jawar)",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 3825,
    "min_price": 1600,
    "max_price": 2200,
    "modal_price": 1900,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Sorgum(Jawar)",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 2093,
    "min_price": 1695,
    "max_price": 2454,
    "modal_price": 2119,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Maize",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 75,
    "min_price": 1345,
    "max_price": 1401,
    "modal_price": 1373,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Maize",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 155,
    "min_price": 1367,
    "max_price": 1392,
    "modal_price": 1375,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Gram",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 1794,
    "min_price": 3533,
    "max_price": 3762,
    "modal_price": 3647,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Gram",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 630,
    "min_price": 4790,
    "max_price": 5553,
    "modal_price": 5216,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Horse Gram",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 3,
    "min_price": 7150,
    "max_price": 7150,
    "modal_price": 7150,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Matki",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 1,
    "min_price": 7500,
    "max_price": 7500,
    "modal_price": 7500,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Pigeon Pea (Tur)",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 144,
    "min_price": 4993,
    "max_price": 5373,
    "modal_price": 5233,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Pigeon Pea (Tur)",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 33,
    "min_price": 6900,
    "max_price": 7700,
    "modal_price": 7329,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Black Gram",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 7,
    "min_price": 5700,
    "max_price": 5700,
    "modal_price": 5700,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Black Gram",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 2,
    "min_price": 7500,
    "max_price": 7500,
    "modal_price": 7500,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Castor Seed",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 3,
    "min_price": 3313,
    "max_price": 3313,
    "modal_price": 3313,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Soybean",
    "Year": 2015,
    "Month": "April",
    "arrivals_in_qtl": 12,
    "min_price": 2900,
    "max_price": 3400,
    "modal_price": 3150,
    "date": "2015-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
  {
    "APMC": "Ahmednagar",
    "Commodity": "Soybean",
    "Year": 2016,
    "Month": "April",
    "arrivals_in_qtl": 20,
    "min_price": 2200,
    "max_price": 3900,
    "modal_price": 3603,
    "date": "2016-04",
    "district_name": "Ahmadnagar",
    "state_name": "Maharashtra"
  },
]
