export const data = [
    {
      "APMC": "Ahmednagar",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 79,
      "min_price": 1406,
      "max_price": 1538,
      "modal_price": 1463,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 106,
      "min_price": 1788,
      "max_price": 1925,
      "modal_price": 1875,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 1253,
      "min_price": 1572,
      "max_price": 1890,
      "modal_price": 1731,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 387,
      "min_price": 1750,
      "max_price": 2220,
      "modal_price": 1999,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 3825,
      "min_price": 1600,
      "max_price": 2200,
      "modal_price": 1900,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2093,
      "min_price": 1695,
      "max_price": 2454,
      "modal_price": 2119,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Maize",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 75,
      "min_price": 1345,
      "max_price": 1401,
      "modal_price": 1373,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Maize",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 155,
      "min_price": 1367,
      "max_price": 1392,
      "modal_price": 1375,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 1794,
      "min_price": 3533,
      "max_price": 3762,
      "modal_price": 3647,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 630,
      "min_price": 4790,
      "max_price": 5553,
      "modal_price": 5216,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Horse Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 3,
      "min_price": 7150,
      "max_price": 7150,
      "modal_price": 7150,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Matki",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 1,
      "min_price": 7500,
      "max_price": 7500,
      "modal_price": 7500,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Pigeon Pea (Tur)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 144,
      "min_price": 4993,
      "max_price": 5373,
      "modal_price": 5233,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Pigeon Pea (Tur)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 33,
      "min_price": 6900,
      "max_price": 7700,
      "modal_price": 7329,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Black Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 7,
      "min_price": 5700,
      "max_price": 5700,
      "modal_price": 5700,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Black Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2,
      "min_price": 7500,
      "max_price": 7500,
      "modal_price": 7500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Castor Seed",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 3,
      "min_price": 3313,
      "max_price": 3313,
      "modal_price": 3313,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Soybean",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 12,
      "min_price": 2900,
      "max_price": 3400,
      "modal_price": 3150,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Soybean",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 20,
      "min_price": 2200,
      "max_price": 3900,
      "modal_price": 3603,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Jaggery",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2611,
      "min_price": 2950,
      "max_price": 3550,
      "modal_price": 3263,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Lemon",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 106,
      "min_price": 2750,
      "max_price": 6625,
      "modal_price": 5500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Ginger (Fresh)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 46,
      "min_price": 1667,
      "max_price": 3000,
      "modal_price": 2500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Potato",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 510,
      "min_price": 767,
      "max_price": 1367,
      "modal_price": 1133,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Ladies Finger",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 58,
      "min_price": 1067,
      "max_price": 4000,
      "modal_price": 3000,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Flower",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 180,
      "min_price": 625,
      "max_price": 3375,
      "modal_price": 2138,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Carrot",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 57,
      "min_price": 900,
      "max_price": 1400,
      "modal_price": 1250,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Cluster Bean",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 46,
      "min_price": 4250,
      "max_price": 6875,
      "modal_price": 5750,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Ghevda",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 3,
      "min_price": 4500,
      "max_price": 6000,
      "modal_price": 5250,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Ghosali(Bhaji)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 5,
      "min_price": 1333,
      "max_price": 3667,
      "modal_price": 2833,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Mango(Raw)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 23,
      "min_price": 1000,
      "max_price": 2000,
      "modal_price": 1500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Cucumber",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 202,
      "min_price": 500,
      "max_price": 2050,
      "modal_price": 1500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 186700,
      "min_price": 114,
      "max_price": 1459,
      "modal_price": 797,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 42342,
      "min_price": 100,
      "max_price": 938,
      "modal_price": 538,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Bitter Gourd",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 8,
      "min_price": 5000,
      "max_price": 6333,
      "modal_price": 5667,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Cabbage",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 195,
      "min_price": 275,
      "max_price": 900,
      "modal_price": 675,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Garlic",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 14,
      "min_price": 4500,
      "max_price": 6000,
      "modal_price": 5250,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Math (Bhaji)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 12,
      "min_price": 5,
      "max_price": 13,
      "modal_price": 10,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Capsicum",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 68,
      "min_price": 1333,
      "max_price": 3167,
      "modal_price": 2500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Tomato",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 334,
      "min_price": 350,
      "max_price": 875,
      "modal_price": 700,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Brinjal",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 120,
      "min_price": 625,
      "max_price": 2625,
      "modal_price": 2000,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Tamarind",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 11701,
      "min_price": 5486,
      "max_price": 9309,
      "modal_price": 7398,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Tamarind",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 9150,
      "min_price": 6989,
      "max_price": 10229,
      "modal_price": 8481,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Tamarind Seed",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 8,
      "min_price": 1480,
      "max_price": 1480,
      "modal_price": 1480,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Tamarind Seed",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 215,
      "min_price": 1804,
      "max_price": 1804,
      "modal_price": 1804,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Coriander (Dry)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 151,
      "min_price": 7000,
      "max_price": 12000,
      "modal_price": 9500,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Coriander (Dry)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 269,
      "min_price": 6900,
      "max_price": 9600,
      "modal_price": 8250,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Green Chilli",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 138,
      "min_price": 3333,
      "max_price": 7000,
      "modal_price": 5333,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Chillies(Red)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 792,
      "min_price": 5284,
      "max_price": 8952,
      "modal_price": 7118,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Chillies(Red)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1900,
      "min_price": 7925,
      "max_price": 12313,
      "modal_price": 10185,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Mustard",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 22,
      "min_price": 3617,
      "max_price": 3617,
      "modal_price": 3617,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Ahmednagar",
      "Commodity": "Mustard",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2,
      "min_price": 3800,
      "max_price": 3800,
      "modal_price": 3800,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 52,
      "min_price": 1357,
      "max_price": 1800,
      "modal_price": 1525,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 75,
      "min_price": 1460,
      "max_price": 1960,
      "modal_price": 1685,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Paddy-Unhusked",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 113,
      "min_price": 1450,
      "max_price": 1925,
      "modal_price": 1625,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Paddy-Unhusked",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 448,
      "min_price": 1500,
      "max_price": 2017,
      "modal_price": 1704,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 164,
      "min_price": 1450,
      "max_price": 1975,
      "modal_price": 1644,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 115,
      "min_price": 1517,
      "max_price": 2150,
      "modal_price": 1725,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 39,
      "min_price": 3200,
      "max_price": 3500,
      "modal_price": 3350,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 70,
      "min_price": 3767,
      "max_price": 4833,
      "modal_price": 4383,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Soybean",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 285,
      "min_price": 3000,
      "max_price": 3450,
      "modal_price": 3250,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Soybean",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 378,
      "min_price": 3400,
      "max_price": 3883,
      "modal_price": 3683,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 105645,
      "min_price": 106,
      "max_price": 1389,
      "modal_price": 849,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 56372,
      "min_price": 150,
      "max_price": 973,
      "modal_price": 662,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Akole",
      "Commodity": "Hilda",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 34,
      "min_price": 5000,
      "max_price": 7000,
      "modal_price": 6000,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 164,
      "min_price": 1304,
      "max_price": 1446,
      "modal_price": 1375,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 45,
      "min_price": 1513,
      "max_price": 1742,
      "modal_price": 1627,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 735,
      "min_price": 1856,
      "max_price": 2256,
      "modal_price": 2056,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 46,
      "min_price": 2132,
      "max_price": 2268,
      "modal_price": 2200,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 20890,
      "min_price": 1800,
      "max_price": 2800,
      "modal_price": 2300,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 24391,
      "min_price": 1861,
      "max_price": 2933,
      "modal_price": 2397,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 931,
      "min_price": 3175,
      "max_price": 3397,
      "modal_price": 3286,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 521,
      "min_price": 4088,
      "max_price": 4833,
      "modal_price": 4460,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Pigeon Pea (Tur)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 191,
      "min_price": 6825,
      "max_price": 7452,
      "modal_price": 7143,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Soybean",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 99,
      "min_price": 3084,
      "max_price": 3466,
      "modal_price": 3275,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 5232,
      "min_price": 106,
      "max_price": 1469,
      "modal_price": 788,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Jamkhed",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 7587,
      "min_price": 100,
      "max_price": 939,
      "modal_price": 519,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 354,
      "min_price": 1164,
      "max_price": 1469,
      "modal_price": 1401,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 388,
      "min_price": 1603,
      "max_price": 2018,
      "modal_price": 1750,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 9668,
      "min_price": 1302,
      "max_price": 1713,
      "modal_price": 1529,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1028,
      "min_price": 1486,
      "max_price": 1861,
      "modal_price": 1652,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 672,
      "min_price": 1070,
      "max_price": 1421,
      "modal_price": 1324,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2038,
      "min_price": 1445,
      "max_price": 1974,
      "modal_price": 1770,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Maize",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 389,
      "min_price": 1156,
      "max_price": 1257,
      "modal_price": 1226,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Maize",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 284,
      "min_price": 1373,
      "max_price": 1445,
      "modal_price": 1418,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 2378,
      "min_price": 3214,
      "max_price": 3822,
      "modal_price": 3681,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 748,
      "min_price": 4492,
      "max_price": 5435,
      "modal_price": 5276,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Pigeon Pea (Tur)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 6,
      "min_price": 4880,
      "max_price": 4921,
      "modal_price": 4900,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Soybean",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 329,
      "min_price": 3244,
      "max_price": 3590,
      "modal_price": 3517,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Soybean",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 175,
      "min_price": 3728,
      "max_price": 3950,
      "modal_price": 3893,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Chikoo",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 1107,
      "min_price": 500,
      "max_price": 2200,
      "modal_price": 1120,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 34179,
      "min_price": 395,
      "max_price": 1350,
      "modal_price": 988,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Kopargaon",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 18750,
      "min_price": 250,
      "max_price": 845,
      "modal_price": 701,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 32,
      "min_price": 1282,
      "max_price": 1293,
      "modal_price": 1286,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2,
      "min_price": 1750,
      "max_price": 1750,
      "modal_price": 1750,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 575,
      "min_price": 1450,
      "max_price": 1511,
      "modal_price": 1481,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 135,
      "min_price": 1608,
      "max_price": 1900,
      "modal_price": 1667,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 25,
      "min_price": 1550,
      "max_price": 1550,
      "modal_price": 1550,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 37,
      "min_price": 1658,
      "max_price": 1708,
      "modal_price": 1679,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Maize",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 13,
      "min_price": 1310,
      "max_price": 1310,
      "modal_price": 1310,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 180,
      "min_price": 3200,
      "max_price": 3271,
      "modal_price": 3229,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 64,
      "min_price": 4383,
      "max_price": 4783,
      "modal_price": 4483,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Tamarind",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 23,
      "min_price": 1200,
      "max_price": 1225,
      "modal_price": 1213,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa",
      "Commodity": "Tamarind",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 5,
      "min_price": 2350,
      "max_price": 2350,
      "modal_price": 2350,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa-Ghodegaon",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 186038,
      "min_price": 285,
      "max_price": 1342,
      "modal_price": 977,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Newasa-Ghodegaon",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 231700,
      "min_price": 200,
      "max_price": 921,
      "modal_price": 717,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Parner",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 78184,
      "min_price": 500,
      "max_price": 1430,
      "modal_price": 965,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Parner",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 144673,
      "min_price": 300,
      "max_price": 919,
      "modal_price": 685,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Cotton",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 470,
      "min_price": 3760,
      "max_price": 3860,
      "modal_price": 3807,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 371,
      "min_price": 1259,
      "max_price": 1443,
      "modal_price": 1317,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 163,
      "min_price": 1285,
      "max_price": 1650,
      "modal_price": 1449,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 685,
      "min_price": 1489,
      "max_price": 2133,
      "modal_price": 1761,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 343,
      "min_price": 1583,
      "max_price": 2133,
      "modal_price": 1855,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 734,
      "min_price": 1528,
      "max_price": 1783,
      "modal_price": 1648,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 682,
      "min_price": 1573,
      "max_price": 1935,
      "modal_price": 1740,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 164,
      "min_price": 3300,
      "max_price": 3663,
      "modal_price": 3494,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 171,
      "min_price": 3683,
      "max_price": 4675,
      "modal_price": 4458,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 3133,
      "min_price": 238,
      "max_price": 1433,
      "modal_price": 920,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Pathardi",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 4703,
      "min_price": 173,
      "max_price": 1605,
      "modal_price": 696,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 203,
      "min_price": 1168,
      "max_price": 1268,
      "modal_price": 1223,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 39,
      "min_price": 1511,
      "max_price": 1511,
      "modal_price": 1511,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 2698,
      "min_price": 1292,
      "max_price": 1589,
      "modal_price": 1394,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 346,
      "min_price": 1495,
      "max_price": 1677,
      "modal_price": 1572,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 589,
      "min_price": 1123,
      "max_price": 1315,
      "modal_price": 1217,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 543,
      "min_price": 1442,
      "max_price": 1611,
      "modal_price": 1541,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Maize",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 366,
      "min_price": 1266,
      "max_price": 1326,
      "modal_price": 1283,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Maize",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 297,
      "min_price": 1379,
      "max_price": 1398,
      "modal_price": 1379,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 950,
      "min_price": 3335,
      "max_price": 3694,
      "modal_price": 3557,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 70,
      "min_price": 4568,
      "max_price": 4678,
      "modal_price": 4618,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Pigeon Pea (Tur)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2,
      "min_price": 6050,
      "max_price": 6050,
      "modal_price": 6050,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ground Nut Pods (Dry)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 38,
      "min_price": 2675,
      "max_price": 2942,
      "modal_price": 2717,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ground Nut Pods (Dry)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 2,
      "min_price": 3200,
      "max_price": 3200,
      "modal_price": 3200,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Soybean",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 93,
      "min_price": 3382,
      "max_price": 3407,
      "modal_price": 3391,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Soybean",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 35,
      "min_price": 3879,
      "max_price": 3902,
      "modal_price": 3882,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Pomegranate",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 9318,
      "min_price": 1500,
      "max_price": 15413,
      "modal_price": 8565,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Pomegranate",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 40216,
      "min_price": 1000,
      "max_price": 9928,
      "modal_price": 5860,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Lemon",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 17,
      "min_price": 6278,
      "max_price": 6611,
      "modal_price": 6444,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Lemon",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 14,
      "min_price": 5773,
      "max_price": 6091,
      "modal_price": 5955,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Papai",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 34,
      "min_price": 344,
      "max_price": 475,
      "modal_price": 375,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Melon",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 3,
      "min_price": 400,
      "max_price": 400,
      "modal_price": 400,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ginger (Fresh)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 31,
      "min_price": 3125,
      "max_price": 3417,
      "modal_price": 3242,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ginger (Fresh)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 39,
      "min_price": 1550,
      "max_price": 2167,
      "modal_price": 1792,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Potato",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 1467,
      "min_price": 588,
      "max_price": 1346,
      "modal_price": 696,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Potato",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 851,
      "min_price": 1192,
      "max_price": 1542,
      "modal_price": 1392,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Beet Root",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 17,
      "min_price": 1000,
      "max_price": 1278,
      "modal_price": 1022,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ladies Finger",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 86,
      "min_price": 1333,
      "max_price": 2208,
      "modal_price": 1767,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ladies Finger",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 83,
      "min_price": 2136,
      "max_price": 2955,
      "modal_price": 2564,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Bottle Gourd",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 196,
      "min_price": 377,
      "max_price": 608,
      "modal_price": 462,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Bottle Gourd",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 60,
      "min_price": 1655,
      "max_price": 2180,
      "modal_price": 1930,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Dhemse",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1,
      "min_price": 2000,
      "max_price": 2000,
      "modal_price": 2000,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Flower",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 158,
      "min_price": 1200,
      "max_price": 1950,
      "modal_price": 1583,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Carrot",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 9,
      "min_price": 1650,
      "max_price": 1713,
      "modal_price": 1650,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Carrot",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 34,
      "min_price": 1255,
      "max_price": 1545,
      "modal_price": 1327,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Cluster Bean",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 28,
      "min_price": 2350,
      "max_price": 2900,
      "modal_price": 2640,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Cluster Bean",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 16,
      "min_price": 4889,
      "max_price": 5444,
      "modal_price": 5000,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ghevda",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 9,
      "min_price": 3938,
      "max_price": 4063,
      "modal_price": 3938,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Ghevda",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 7,
      "min_price": 6143,
      "max_price": 6286,
      "modal_price": 6143,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Mango(Raw)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 13,
      "min_price": 1333,
      "max_price": 1667,
      "modal_price": 1500,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Mango(Raw)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 22,
      "min_price": 2063,
      "max_price": 2375,
      "modal_price": 2088,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Cucumber",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 124,
      "min_price": 500,
      "max_price": 1478,
      "modal_price": 611,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Cucumber",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 73,
      "min_price": 1483,
      "max_price": 2000,
      "modal_price": 1733,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 107650,
      "min_price": 222,
      "max_price": 1467,
      "modal_price": 906,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Onion",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 64671,
      "min_price": 100,
      "max_price": 925,
      "modal_price": 619,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Bitter Gourd",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 20,
      "min_price": 2571,
      "max_price": 2843,
      "modal_price": 2671,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Bitter Gourd",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 5,
      "min_price": 6300,
      "max_price": 6300,
      "modal_price": 6300,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Cabbage",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 900,
      "min_price": 5,
      "max_price": 6,
      "modal_price": 5,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Cabbage",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 302,
      "min_price": 417,
      "max_price": 708,
      "modal_price": 550,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Coriander",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 100,
      "min_price": 4,
      "max_price": 6,
      "modal_price": 4,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Coriander",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1400,
      "min_price": 15,
      "max_price": 25,
      "modal_price": 18,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Garlic",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 57,
      "min_price": 2692,
      "max_price": 3192,
      "modal_price": 2915,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Garlic",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 68,
      "min_price": 4000,
      "max_price": 5750,
      "modal_price": 4767,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Math (Bhaji)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 400,
      "min_price": 20,
      "max_price": 20,
      "modal_price": 20,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Capsicum",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 46,
      "min_price": 1904,
      "max_price": 2442,
      "modal_price": 2135,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Capsicum",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 124,
      "min_price": 1938,
      "max_price": 2733,
      "modal_price": 2317,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Spinach",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 250,
      "min_price": 5,
      "max_price": 5,
      "modal_price": 5,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Shevga",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 29,
      "min_price": 1791,
      "max_price": 2200,
      "modal_price": 1945,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Shevga",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 66,
      "min_price": 608,
      "max_price": 850,
      "modal_price": 675,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Tomato",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 281,
      "min_price": 492,
      "max_price": 1223,
      "modal_price": 869,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Tomato",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 287,
      "min_price": 425,
      "max_price": 788,
      "modal_price": 558,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Small Gourd",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 6,
      "min_price": 2233,
      "max_price": 2400,
      "modal_price": 2300,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Small Gourd",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 4,
      "min_price": 2500,
      "max_price": 3000,
      "modal_price": 2750,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Brinjal",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 77,
      "min_price": 577,
      "max_price": 977,
      "modal_price": 762,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Brinjal",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 79,
      "min_price": 1158,
      "max_price": 1783,
      "modal_price": 1533,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Green Chilli",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 133,
      "min_price": 3500,
      "max_price": 5692,
      "modal_price": 4554,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Green Chilli",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 197,
      "min_price": 4045,
      "max_price": 6027,
      "modal_price": 5136,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 42,
      "min_price": 1380,
      "max_price": 1380,
      "modal_price": 1380,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 2403,
      "min_price": 1402,
      "max_price": 1498,
      "modal_price": 1450,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 18,
      "min_price": 1583,
      "max_price": 1583,
      "modal_price": 1583,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Maize",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 26,
      "min_price": 1310,
      "max_price": 1310,
      "modal_price": 1310,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 328,
      "min_price": 3257,
      "max_price": 3405,
      "modal_price": 3333,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Chikoo",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 475,
      "min_price": 436,
      "max_price": 2322,
      "modal_price": 1383,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Pomegranate",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 496,
      "min_price": 200,
      "max_price": 4946,
      "modal_price": 2573,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Grapes",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 66,
      "min_price": 1529,
      "max_price": 3250,
      "modal_price": 2389,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Melon",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1301,
      "min_price": 244,
      "max_price": 1013,
      "modal_price": 631,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Kharbuj",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 567,
      "min_price": 333,
      "max_price": 2038,
      "modal_price": 1178,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Onion",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 123030,
      "min_price": 100,
      "max_price": 1389,
      "modal_price": 739,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Bajri",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 87,
      "min_price": 1373,
      "max_price": 1474,
      "modal_price": 1422,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Bajri",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 20,
      "min_price": 1716,
      "max_price": 1763,
      "modal_price": 1739,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Wheat(Husked)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 2494,
      "min_price": 1280,
      "max_price": 1836,
      "modal_price": 1679,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Wheat(Husked)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 321,
      "min_price": 1567,
      "max_price": 1829,
      "modal_price": 1700,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 830,
      "min_price": 1255,
      "max_price": 1500,
      "modal_price": 1377,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Sorgum(Jawar)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 551,
      "min_price": 1436,
      "max_price": 1957,
      "modal_price": 1720,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Maize",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 54,
      "min_price": 1275,
      "max_price": 1278,
      "modal_price": 1276,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Maize",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 7,
      "min_price": 1298,
      "max_price": 1298,
      "modal_price": 1298,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 1089,
      "min_price": 3433,
      "max_price": 3690,
      "modal_price": 3561,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1038,
      "min_price": 4980,
      "max_price": 5945,
      "modal_price": 5467,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Matki",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1,
      "min_price": 6500,
      "max_price": 6500,
      "modal_price": 6500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Green Gram",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 3,
      "min_price": 7600,
      "max_price": 7600,
      "modal_price": 7600,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Green Gram",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 7,
      "min_price": 7033,
      "max_price": 7356,
      "modal_price": 7194,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Pigeon Pea (Tur)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 63,
      "min_price": 4900,
      "max_price": 5230,
      "modal_price": 5115,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Pigeon Pea (Tur)",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 19,
      "min_price": 7464,
      "max_price": 7503,
      "modal_price": 7484,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Ground Nut Pods (Dry)",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 33,
      "min_price": 3588,
      "max_price": 3613,
      "modal_price": 3601,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
]